language: node_js
node_js:
- '4.2'
env:
  global:
  - DEPLOY_BRANCH=master
  - secure: zH83XQ1nLWk99Y6S8DrbdREvnmXR2tvt0ox5iNLUC2hiN1+cChlJIvWe/0Wx730oMR91+27HhzGuTdUD5bMb6IB10+TsNCoywy8u4f0unmG1LHbL61iltHPbxJixAWJpwEKbAFWJMxnVAJgP2bDo/BKeXXYuR07wPGC2HjEU22IPp+7Flnc3PxQOkFMmHTAvSRXf8ut86mhuYRnhldBwvg/4ARmP57zFcvk0Yi/rPR4TNNVaUgFbX9hMWu9PifF+sFZ45FWw2l8t9aWY1CE+IvHo8AjZnKzn+rWL83YFmPCKB5AaZWlo0gRZEKglk7v85TkC3ISig9xvvBpnEvtBW4VvZdHcOAzdr0NvAs6iizKfQH3WK0f72L9zI1lf1TFQahgT5FAbKXtIoUYq1FUW1rClzHJyMnfmfFeOl2mCWADRdE0aPwNsw/GrXPxazTGAmJQ+HJIr4y+tGMSeFmvxsOSRJwvFwCR22/d1XrEyqvecp+BSAjAa/RxBMOlnNmLrCjT5F03qze02xIItVdp/5bbCkBzli6Xyb308OGmHDylAehe2feEjJFPcJb+kLRJb952fYX7hft0tC0M2gfsfIESQrsMq3Q+NV30rrH106hf4LJPr8FWI8ekphJ9qczx1UWe8k+g2DWxZ6KWAdmczy6Y6O7EuaFjGJYINph3YeW8=
  - secure: gxXNIRBeQ+cBEcpVBSbd5rMmLSF9aDPytRQpnvnqUhY+gUs4oU7axx5WgnfW5wV5op5UJ2BnF70KSNmMmOx3VwylhfYkbNasfcK6rQIRNdko70WHK4+cCAPatgnv3urG5W2T+BgBaoFFo1i/1otKTX95oOwLsp2ZPDjaOa6lxoTMcrbO/rn5p4SsStR6B9XsW/+mZJtBOPf5ZF0BlTf1hweUkPhMMzys+r5Blv3PcRvwxT7mCdV40dwmUHP/VsXZEE6AIrKplILasAMo9xrr8XKq3DOzgQFN9QIRk8zvWjwcxZeJhsouBC0KiY+dEcYSCgTxbAwwDsXpTKbhuLaMraWhbCDpJyQ+9XwDjH6nDQKMQbNt5imR+eDZVo7mnb0K0XMiPIHmy5xMOLFSuHR8f7cH2JS0K/5SXlNizRES5akCWOb2ollX6JC4R8ExXzBS3b7WBsWYChrRUAvX3xlDT1HjbgN4hspkI9gAK5+dScnloLpJMlAC4slkTQE0cvUPJDrUO8JCRW6zEa2vGv/cJFYAwuKnX5tA+xcDGJdPEG9MRzd12V5pFkirfj4YdC5C058nXAN9ALSWzkBDDH0V7J3X3kWC9XO1lhxjLHPon8+uI+OkdfxMZinyozyTk9MzzOmNG+OpVWmM/jUN8lJW1I5kD9VCCzznkHk0DrnbBlw=
  - secure: kJ/VMRbnYD/L0WRbztovuvGcAcbSo7nwQ2EQoX+4nnMM5FE+tZXfWDMn+FgZnv8lAFY/pqKPvlO5VkxvMgBgmQqCTRNNJcnhphVT0pr5sS9UB4smObz2+DmetTII6RI9hZcOYhBko1S4ommVdQYLxe/en1i36HKPasq9R0e+Lbn1xFRDB4Kc0Obzfn/1VDEyFXF7LiL61zP97sFBgoKrnBF2mFBMHnjsUofivbIybWEmUERQlUhSHtSoKcbnyxvsazRBxw+hS52m2mDgJTzU/h1S9O1rRtsP74+zd/96xJC2OLu8yQMF5z0mlcqXOAb1UwifF3+cIRSsH9xNL0yy5szV4yKiGMHvkTBhm04i8n062gVQSbqk/b5O/VCrq9bOK568yG4/uzCppjnu/Sbr/IErz30VLER4R0w4pgnPEKZ9Vd6afI237P9HmEe6m4wztXtHnYgqPa4r1/I43hhxs1WK1JqZ820aQLRwEh6S070qgXFbOH7ynkTSTy3fKxpKPU0ak+qWzlT71Wp6kmIbuZpgOqlFL0H11M4DPMF7H71jaPCiaB9MDUFqb3GMrgbzT7YraLJOFCmPaStteLyA0dIwdx46+5T9WKJB5Ta3zmsljNFiz7ueUR1hLDWD9w/JY2Nfgdo0g14YHwc8zNqY6DnTU6O+Fak5kV/FR/E2Onc=
cache:
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/precalc.js
before_script:
- npm test
- node ./.build_scripts/precalc.js
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
